name: fordev
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  equatable: ^2.0.5
  http: ^1.2.1
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.11
  faker: ^2.1.0
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.0
  mockito: ^5.4.4
  test: ^1.25.2

flutter:
  uses-material-design: true
  assets:
    - lib/ui/assets/

flutter_launcher_icons:
  ios: true
  android: true
  image_path_android: lib/ui/assets/icon/android.png
  image_path_ios: lib/ui/assets/icon/ios.png
  remove_alpha_ios: true